[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "pypathkit"
version = "0.1.0"
description = "Simple file management utilities for Python"
readme = "README.md"
requires-python = ">=3.8"

authors = [
    {name = "Amir"}
]

[tool.setuptools.packages.find]
where = ["src"]
